import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ 
  children, 
  }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased 
        bg-cover bg-center bg-no-repeat
        bg-[url('images/bg-light.png')] 
        dark:bg-[url('app/images/bg-dark.png)]
        min-h-screen 
        flex 
        items-center 
        justify-center`} 
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem 
          disapleTransitionOnChange
        >{children}</ThemeProvider>
      </body>
    </html>
  );
}
